# Generated by Django 2.2.3 on 2020-02-26 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20200226_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voicemessage',
            old_name='file_field',
            new_name='voice_field',
        ),
    ]
