# Generated by Django 2.2.3 on 2020-02-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_soldproduct_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldtimeslotsale',
            name='end_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldtimeslotsale',
            name='start_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
