# Generated by Django 2.1.3 on 2019-02-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190221_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
