# Generated by Django 2.1.3 on 2019-03-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190303_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='field',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='university',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
