# Generated by Django 2.2.3 on 2020-02-12 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, help_text='Leave this field blank.', max_length=12)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('canceled_not_refunded', 'Canceled but not refunded'), ('canceled_refunded', 'Canceled and refunded')], default='paid', max_length=256)),
                ('cart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_order', to='carts.SoldCart')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, help_text='Leave this field blank.', max_length=12)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('created', 'Created')], default='created', max_length=256)),
                ('cart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_order', to='carts.Cart')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
