# Generated by Django 2.2.3 on 2020-03-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, help_text='Leave this field blank, this will populate automatically.', max_length=12, unique=True),
        ),
    ]
