# Generated by Django 2.2.3 on 2020-02-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoldOrder',
        ),
    ]
