# Generated by Django 2.2.3 on 2020-03-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200301_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='used_consultant_discount',
            new_name='used_discount',
        ),
    ]
