# Generated by Django 2.2.3 on 2020-02-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_soldorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, help_text='Leave this field blank, this will populate automatically.', max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('canceled_not_refunded', 'Canceled but not refunded'), ('canceled_refunded', 'Canceled and refunded')], default='paid', max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
