# Generated by Django 2.2.3 on 2020-02-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200221_0702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='used_discount',
        ),
    ]
