# Generated by Django 2.2.3 on 2019-07-21 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190721_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_order', to='carts.Cart'),
        ),
        migrations.AlterField(
            model_name='soldorder',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_order', to='carts.SoldCart'),
        ),
    ]
