# Generated by Django 2.2.3 on 2019-08-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketMessage',
            new_name='Message',
        ),
    ]
