# Generated by Django 2.2.3 on 2020-03-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='picture',
            field=models.ImageField(upload_to='account/images/country-pictures'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='picture',
            field=models.ImageField(upload_to='account/images/field-of-study-pictures'),
        ),
        migrations.AlterField(
            model_name='university',
            name='picture',
            field=models.ImageField(upload_to='account/images/university-pictures'),
        ),
    ]
