# Generated by Django 2.2.3 on 2020-04-01 16:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sNeeds.apps.account.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20200325_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetailedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)])),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('single', 'Single')], max_length=32)),
                ('grade', models.CharField(choices=[('college', 'College'), ('associate', 'Associate'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('doctoral', 'Doctoral')], max_length=64)),
                ('university', models.CharField(max_length=128)),
                ('total_average', models.DecimalField(decimal_places=2, max_digits=4)),
                ('degree_conferral_year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=sNeeds.apps.account.models.current_year, verbose_name='year')),
                ('major', models.CharField(max_length=128)),
                ('thesis_title', models.CharField(blank=True, max_length=512, null=True)),
                ('language_certificate', models.CharField(choices=[('ielts_academic', 'IELTS Academic'), ('ielts_general', 'IELTS General'), ('toefl', 'TOEFL'), ('duolingo', 'Duolingo'), ('iaeste', 'IAESTE'), ('gre', 'GRE'), ('gmat', 'GMAT')], max_length=64)),
                ('language_certificate_overall', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('language_speaking', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('language_listening', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('language_writing', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('language_reading', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mainland', models.CharField(choices=[('asia', 'Asia'), ('europe', 'Europe'), ('north_america', 'North America'), ('australia', 'Australia')], max_length=32)),
                ('country', models.CharField(max_length=128)),
                ('apply_grade', models.CharField(choices=[('college', 'College'), ('associate', 'Associate'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('doctoral', 'Doctoral'), ('post_doc', 'Post Doctoral')], max_length=64)),
                ('apply_major', models.CharField(max_length=128)),
                ('comment', models.TextField(blank=True, max_length=1024, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to=sNeeds.apps.account.models.get_student_resume_path)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
