# Generated by Django 2.2.3 on 2019-07-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190713_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='countries',
            field=models.ManyToManyField(null=True, to='account.Country'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='field_of_studies',
            field=models.ManyToManyField(null=True, to='account.FieldOfStudy'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='universities',
            field=models.ManyToManyField(null=True, to='account.University'),
        ),
    ]
