# Generated by Django 2.2.3 on 2020-04-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_studentdetailedinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='degree_conferral_year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
