# Generated by Django 2.2.3 on 2019-07-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190721_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='countries',
            field=models.ManyToManyField(blank=True, to='account.Country'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='field_of_studies',
            field=models.ManyToManyField(blank=True, to='account.FieldOfStudy'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='universities',
            field=models.ManyToManyField(blank=True, to='account.University'),
        ),
    ]
