# Generated by Django 2.2.3 on 2020-04-02 12:18

from django.db import migrations, models
import sNeeds.apps.account.validators


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200402_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='apply_grade',
            field=models.CharField(choices=[('college', 'College'), ('associate', 'Associate'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('doctoral', 'Doctoral'), ('post_doc', 'Post Doctoral')], max_length=64, validators=[sNeeds.apps.account.validators.validate_apply_grade]),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='grade',
            field=models.CharField(choices=[('college', 'College'), ('associate', 'Associate'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('doctoral', 'Doctoral')], max_length=64, validators=[sNeeds.apps.account.validators.validate_grade]),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='language_certificate',
            field=models.CharField(choices=[('ielts_academic', 'IELTS Academic'), ('ielts_general', 'IELTS General'), ('toefl', 'TOEFL'), ('duolingo', 'Duolingo'), ('iaeste', 'IAESTE'), ('gre', 'GRE'), ('gmat', 'GMAT')], max_length=64, validators=[sNeeds.apps.account.validators.validate_language_certificate]),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='mainland',
            field=models.CharField(choices=[('asia', 'Asia'), ('europe', 'Europe'), ('north_america', 'North America'), ('australia', 'Australia')], max_length=32, validators=[sNeeds.apps.account.validators.validate_mainland]),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('single', 'Single')], max_length=32, validators=[sNeeds.apps.account.validators.validate_marital_status]),
        ),
    ]
