# Generated by Django 2.2.3 on 2019-07-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190721_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
