# Generated by Django 2.2.3 on 2020-04-05 10:07

from django.db import migrations, models
import sNeeds.apps.account.validators


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200402_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='apply_grade',
            field=models.CharField(choices=[('college', 'College'), ('associate', 'Associate'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('doctoral', 'Doctoral'), ('post_doctoral', 'Post Doctoral')], max_length=64, validators=[sNeeds.apps.account.validators.validate_apply_grade]),
        ),
    ]
