# Generated by Django 2.2.3 on 2020-04-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200405_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='fieldofstudy',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name']},
        ),
    ]
