# Generated by Django 2.2.3 on 2019-07-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190722_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='profile_picture',
            field=models.ImageField(upload_to='consultant_profile_pictures'),
        ),
    ]
