# Generated by Django 2.2.3 on 2019-07-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190722_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='profile_picture',
            field=models.ImageField(upload_to='static/media/pictures/consultant_profile_pictures'),
        ),
        migrations.AlterField(
            model_name='country',
            name='picture',
            field=models.ImageField(upload_to='static/media/pictures/country_pictures'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='picture',
            field=models.ImageField(upload_to='static/media/pictures/field_of_study_pictures'),
        ),
        migrations.AlterField(
            model_name='university',
            name='picture',
            field=models.ImageField(upload_to='static/media/pictures/university_pictures'),
        ),
    ]
