# Generated by Django 2.2.3 on 2020-06-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_studentdetailedinfo_studentformapplysemesteryear_studentformfieldschoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='apply_major',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='apply_university',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='degree_conferral_year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='major',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='university',
            field=models.CharField(max_length=256),
        ),
    ]
