# Generated by Django 2.2.3 on 2020-06-15 18:51

import django.core.validators
from django.db import migrations, models
import sNeeds.apps.account.models
import sNeeds.apps.account.validators


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200608_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='language_listening',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='language_reading',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='language_speaking',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='language_writing',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=sNeeds.apps.account.models.get_student_resume_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), sNeeds.apps.account.validators.validate_resume_file_size]),
        ),
    ]
