# Generated by Django 2.2.3 on 2020-06-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200615_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentformfieldschoice',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='studentformfieldschoice',
            name='slug',
            field=models.SlugField(help_text='Lowercase pls'),
        ),
        migrations.AlterUniqueTogether(
            name='studentformfieldschoice',
            unique_together={('category', 'name')},
        ),
    ]
