# Generated by Django 2.2.3 on 2020-06-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200627_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentformfieldschoice',
            name='slug',
        ),
        migrations.AlterField(
            model_name='studentformfieldschoice',
            name='category',
            field=models.CharField(choices=[('grade', 'grade'), ('apply_grade', 'apply_grade'), ('apply_country', 'apply_country'), ('apply_mainland', 'apply_mainland'), ('marital_status', 'marital_status'), ('language_certificate', 'language_certificate')], max_length=256),
        ),
    ]
