# Generated by Django 2.2.3 on 2019-08-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20190730_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='slug',
            field=models.SlugField(help_text='lowercase pls', unique=True),
        ),
    ]
