# Generated by Django 2.2.3 on 2019-09-11 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20190911_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyfield',
            name='name',
            field=models.CharField(choices=[(None, 'Choose your field of study'), ('Math', 'ریاضی و فیزیک'),
                                            ('Natural Science', 'علوم تجربی'), ('Human Science', 'علوم انسانی')],
                                   max_length=16),
        ),
    ]
