# Generated by Django 2.2.3 on 2019-09-16 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20190911_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantprofile',
            name='countries',
        ),
    ]
