# Generated by Django 2.2.3 on 2019-09-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_consultantprofile_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantprofile',
            name='countries',
        ),
    ]
