# Generated by Django 2.2.3 on 2019-09-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_remove_consultantprofile_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='countries',
            field=models.ManyToManyField(blank=True, to='account.Country'),
        ),
    ]
