# Generated by Django 2.2.3 on 2020-02-12 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('customAuth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldtimeslotrate',
            name='sold_time_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.SoldTimeSlotSale'),
        ),
        migrations.AddField(
            model_name='comment',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAuth.ConsultantProfile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admincomment',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_reply', to='comments.Comment'),
        ),
    ]
