# Generated by Django 2.2.3 on 2020-05-24 11:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('basicProducts', '0003_auto_20200524_1615'),
        ('comments', '0002_auto_20200229_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicProductRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rate', models.FloatField(blank=True, default=0, null=True)),
                ('basic_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basicProducts.BasicProduct')),
            ],
        ),
        migrations.CreateModel(
            name='BasicProductRateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('avg_rate', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('basic_product_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comments.BasicProductRate')),
            ],
        ),
        migrations.CreateModel(
            name='SoldBasicProductRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SoldBasicProductRateFieldThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('basic_product_rate_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.BasicProductRateField')),
                ('sold_basic_product_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.SoldBasicProductRate')),
            ],
        ),
        migrations.AddField(
            model_name='soldbasicproductrate',
            name='rates',
            field=models.ManyToManyField(through='comments.SoldBasicProductRateFieldThrough', to='comments.BasicProductRateField'),
        ),
        migrations.AddField(
            model_name='soldbasicproductrate',
            name='sold_basic_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basicProducts.SoldBasicProduct'),
        ),
    ]
