# Generated by Django 2.2.3 on 2020-02-28 18:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0004_comment_reply_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='ConsultantComment',
        ),
    ]
