# Generated by Django 2.2.3 on 2020-02-28 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20200228_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantcomment',
            name='reply_to',
        ),
        migrations.CreateModel(
            name='AdminConsultantComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_reply', to='comments.ConsultantComment')),
            ],
        ),
    ]
