# Generated by Django 2.2.3 on 2020-02-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20200228_1829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminConsultantComment',
            new_name='ConsultantAdminComment',
        ),
    ]
