# Generated by Django 2.2.3 on 2019-10-03 08:20

import django.core.validators
from django.db import migrations, models
import sNeeds.apps.chats.models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_field',
            field=models.FileField(default=None, upload_to=sNeeds.apps.chats.models.get_file_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='image_field',
            field=models.ImageField(default=None, upload_to=sNeeds.apps.chats.models.get_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textmessage',
            name='text_message',
            field=models.CharField(default=None, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voice',
            name='file_field',
            field=models.FileField(default=None, upload_to=sNeeds.apps.chats.models.get_voice_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
            preserve_default=False,
        ),
    ]
