# Generated by Django 2.2.3 on 2019-10-03 08:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_auto_20191003_0820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='FileMessage',
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageMessage',
        ),
        migrations.RenameModel(
            old_name='Voice',
            new_name='VoiceMessage',
        ),
    ]
