# Generated by Django 2.2.3 on 2020-02-26 19:59

import django.core.validators
from django.db import migrations, models
import sNeeds.apps.chats.models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20200229_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicemessage',
            name='file_field',
            field=models.FileField(upload_to=sNeeds.apps.chats.models.get_voice_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'm4a'])]),
        ),
    ]
