# Generated by Django 2.2.3 on 2020-03-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_message_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='tag',
            field=models.IntegerField(editable=False),
        ),
    ]
