# Generated by Django 2.2.3 on 2020-05-15 08:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_auto_20200411_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='text_message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
