# Generated by Django 2.2.3 on 2019-07-23 15:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190722_1304'),
        ('comments', '0004_auto_20190723_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldTimeSlotStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('sold_time_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.SoldTimeSlotSale')),
            ],
        ),
    ]
