# Generated by Django 2.1.3 on 2019-02-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicclass',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
