# Generated by Django 2.2.3 on 2019-07-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20190715_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='time_slots',
            new_name='time_slot_sales',
        ),
    ]
