# Generated by Django 2.2.3 on 2019-07-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20190715_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='time_slot_sales',
            field=models.ManyToManyField(blank=True, to='store.TimeSlotSale'),
        ),
    ]
