# Generated by Django 2.2.3 on 2019-07-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20190722_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldcart',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='soldcart',
            name='time_slot_sales',
            field=models.ManyToManyField(blank=True, to='store.SoldTimeSlotSale'),
        ),
    ]
