# Generated by Django 2.2.3 on 2019-07-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20190725_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldcart',
            old_name='time_slot_sales',
            new_name='sold_time_slot_sales',
        ),
    ]
