# Generated by Django 2.2.3 on 2019-07-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20190717_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='subtotal',
            field=models.IntegerField(blank=True, default=0.0),
        ),
    ]
