# Generated by Django 2.2.3 on 2019-08-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
