# Generated by Django 2.0.5 on 2018-10-21 15:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(default=None, null=True)),
                ('owner', models.CharField(blank=True, default='ناشناس', max_length=200)),
                ('number_of_views', models.IntegerField(default=0, help_text='لطفا مقدار را عوض نکنید ( به جز در مواقع نیاز شدید و باگ)', verbose_name='تعداد بازدید')),
                ('booklet_content', models.FileField(upload_to='website/booklet_content')),
                ('booklet_image', models.ImageField(upload_to='website/booklet_images')),
            ],
        ),
        migrations.CreateModel(
            name='BookletField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, null=True)),
                ('slug', models.SlugField(help_text='Lower case', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookletTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Booklet topic', max_length=120, verbose_name='عنوان')),
                ('slug', models.SlugField(help_text='Lower case', null=True)),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='website.BookletField')),
            ],
        ),
        migrations.CreateModel(
            name='UserUploadedBooklet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('field', models.CharField(max_length=120, verbose_name='رشته')),
                ('topic', models.CharField(max_length=120, verbose_name='درس')),
                ('writer', models.CharField(max_length=120, verbose_name='نویسنده')),
                ('booklet_file', models.FileField(blank=True, null=True, upload_to='website/tmp_booklet_content')),
                ('status', models.CharField(blank=True, choices=[('seen', 'مشاهده شد'), ('pending', 'در حال انجام'), ('finished', 'انجام شد'), ('canceled', 'لغو شد')], default='seen', help_text='وضعیت دانلود و آپلود جزوه اصلی', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='website/post_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
        migrations.AddField(
            model_name='topic',
            name='hello',
            field=models.CharField(default='dd', max_length=120),
        ),
        migrations.AddField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website.Topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=120), unique=True),
        ),
        migrations.AddField(
            model_name='booklet',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booklets', to='website.BookletTopic'),
        ),
    ]
