# Generated by Django 2.0.5 on 2018-10-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181021_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookletPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booklets', models.ManyToManyField(to='website.Booklet')),
            ],
        ),
    ]
