# Generated by Django 2.0.5 on 2018-10-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_bookletpackage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookletpackage',
            name='booklets',
            field=models.ManyToManyField(related_query_name='the_thing', to='website.Booklet'),
        ),
    ]
