# Generated by Django 2.0.5 on 2018-10-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20181022_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookletpackage',
            name='booklets',
            field=models.ManyToManyField(related_name='booklets', to='website.Booklet'),
        ),
    ]
