# Generated by Django 2.0.5 on 2018-09-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20180906_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklet',
            name='booklet_content',
            field=models.FileField(blank=True, upload_to='website/booklet_content'),
        ),
    ]
