# Generated by Django 2.0.5 on 2018-10-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20181022_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookletpackage',
            name='booklets',
        ),
        migrations.DeleteModel(
            name='BookletPackage',
        ),
    ]
