# Generated by Django 2.0.5 on 2018-09-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_booklet_booklet_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
