# Generated by Django 2.0.5 on 2018-09-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20180907_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='booklet_content',
            field=models.FileField(upload_to='website/booklet_content'),
        ),
        migrations.AlterField(
            model_name='booklet',
            name='booklet_image',
            field=models.ImageField(upload_to='website/booklet_images'),
        ),
    ]
