# Generated by Django 2.1.3 on 2019-01-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_bookletproblemreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklet',
            name='teacher',
            field=models.CharField(blank=True, default='ناشناس', max_length=200),
        ),
    ]
