# Generated by Django 2.1.3 on 2019-01-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_booklet_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='hello',
        ),
    ]
