# Generated by Django 2.0.5 on 2018-09-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_topic_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='ad', unique=True),
        ),
    ]
