# Generated by Django 2.0.5 on 2018-09-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_topic_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
        migrations.AddField(
            model_name='topic',
            name='hello',
            field=models.CharField(default='dd', max_length=120),
        ),
    ]
