# Generated by Django 2.0.5 on 2018-09-19 06:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20180919_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=120), unique=True),
        ),
    ]
