# Generated by Django 2.0.5 on 2018-10-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20180919_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='author',
        ),
        migrations.RemoveField(
            model_name='website',
            name='text',
        ),
    ]
