# Generated by Django 2.0.5 on 2018-10-07 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20181007_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookletField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='booklettopic',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='website.BookletField'),
        ),
    ]
