# Generated by Django 2.0.5 on 2018-10-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20181008_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookletfield',
            name='slug',
            field=models.SlugField(help_text='Lower case', null=True),
        ),
        migrations.AlterField(
            model_name='booklettopic',
            name='slug',
            field=models.SlugField(help_text='Lower case', null=True),
        ),
        migrations.AlterField(
            model_name='booklettopic',
            name='subject',
            field=models.CharField(help_text='Booklet topic', max_length=120, verbose_name='عنوان'),
        ),
    ]
