# Generated by Django 2.0.5 on 2018-10-08 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20181008_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklet',
            name='topic',
        ),
        migrations.AddField(
            model_name='booklet',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booklets', to='website.BookletTopic'),
        ),
    ]
