# Generated by Django 2.0.5 on 2018-10-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_useruploadedbooklet'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadedbooklet',
            name='booklet_file',
            field=models.FileField(blank=True, null=True, upload_to='website/tmp_booklet_content'),
        ),
    ]
