# Generated by Django 2.0.5 on 2018-10-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_useruploadedbooklet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadedbooklet',
            name='status',
            field=models.CharField(blank=True, choices=[('seen', 'مشاهده شد'), ('pending', 'در حال انجام'), ('finished', 'انجام شد'), ('canceled', 'لغو شد')], default='seen', help_text='وضعیت دانلود و آپلود جزوه اصلی', max_length=20),
        ),
    ]
