# Generated by Django 2.0.5 on 2018-10-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_booklet_number_of_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
    ]
