# Generated by Django 2.0.5 on 2018-10-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20181017_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
    ]
