# Generated by Django 2.2.3 on 2020-02-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_auto_20200221_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantdiscount',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='consultantdiscount',
            name='start_time',
        ),
    ]
