# Generated by Django 2.0.5 on 2018-10-26 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('information', models.TextField(blank=True, null=True)),
                ('address', models.CharField(default='تهران', max_length=256)),
                ('phone_number', models.CharField(blank=True, max_length=128, null=True)),
                ('slug', models.SlugField(default='default', max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CafeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/cafe_images')),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='discounts.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.IntegerField(blank=True, null=True)),
                ('cafe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='discounts.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='UserDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=128, unique=True)),
                ('discount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_discount', to='discounts.Discount')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_discounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userdiscount',
            unique_together={('discount', 'user')},
        ),
    ]
