# Generated by Django 2.0.5 on 2018-09-11 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='cafe',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='address',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='information',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='cafe',
            name='address',
            field=models.CharField(default='تهران', max_length=256),
        ),
        migrations.AddField(
            model_name='cafe',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='phone_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discounts.Cafe'),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cafeimage',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discounts.Cafe'),
        ),
    ]
