# Generated by Django 2.1.3 on 2018-11-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruseddiscount',
            name='a',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
