# Generated by Django 2.1.3 on 2018-11-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_useruseddiscount_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruseddiscount',
            name='a',
        ),
        migrations.AddField(
            model_name='useruseddiscount',
            name='user_log',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
