# Generated by Django 2.0.5 on 2018-09-16 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_auto_20180911_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeimage',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='discounts.Cafe'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='discounts.Cafe'),
        ),
    ]
