# Generated by Django 2.1.3 on 2018-11-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_auto_20181114_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useruseddiscount',
            old_name='user_log',
            new_name='archive_string',
        ),
    ]
