# Generated by Django 2.1.3 on 2018-11-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_auto_20181120_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruseddiscount',
            name='used_discount_info',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
