# Generated by Django 2.0.5 on 2018-10-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_cafeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiscount',
            name='status',
            field=models.CharField(blank=True, choices=[('not_used', 'استفاده نشده'), ('used', 'استفاده شده')], default='not_used', help_text='آیا استفاده شده یا نه ؟!:D', max_length=20),
        ),
    ]
