# Generated by Django 2.1.3 on 2019-01-23 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_useruseddiscount_used_discount_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruseddiscount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_used_discounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
