# Generated by Django 2.0.5 on 2018-10-29 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discounts', '0005_userdiscount_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUsedDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_discounts1', to='discounts.Discount')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_discounts1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userdiscount',
            name='status',
            field=models.CharField(blank=True, choices=[('not_used', 'استفاده نشده'), ('used', 'استفاده شده')], default='not_used', max_length=20),
        ),
    ]
