# Generated by Django 2.0.5 on 2018-11-01 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0006_auto_20181029_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruseddiscount',
            name='cafe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='used_discounts', to='discounts.Cafe'),
        ),
        migrations.AlterField(
            model_name='useruseddiscount',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_used_discounts', to='discounts.Discount'),
        ),
        migrations.AlterField(
            model_name='useruseddiscount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_used_discounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
