# Generated by Django 2.1.3 on 2018-11-14 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0007_auto_20181101_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userdiscount',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useruseddiscount',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useruseddiscount',
            name='used_discount_information_for_user',
            field=models.CharField(default='نا مشخص', max_length=128),
        ),
        migrations.AlterField(
            model_name='useruseddiscount',
            name='cafe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_discounts', to='discounts.Cafe'),
        ),
        migrations.AlterField(
            model_name='useruseddiscount',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_used_discounts', to='discounts.Discount'),
        ),
    ]
