# Generated by Django 2.1.3 on 2019-02-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0007_auto_20190210_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='information',
            field=models.TextField(),
        ),
    ]
