# Generated by Django 2.0.5 on 2018-11-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0007_auto_20181101_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruseddiscount',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_discounts', to='discounts.Cafe'),
        ),
    ]
