# Generated by Django 2.0.5 on 2018-11-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0008_auto_20181101_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='contact_date',
            field=models.DateField(auto_now=True),
        ),
    ]
