# Generated by Django 2.1.3 on 2019-02-10 16:08

import discounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0009_auto_20190210_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeimage',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='discounts.Cafe'),
        ),
        migrations.AlterField(
            model_name='cafeimage',
            name='image',
            field=models.ImageField(upload_to=discounts.models.upload_post_image),
        ),
        migrations.AlterField(
            model_name='discount',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='discounts.Cafe'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_percent',
            field=models.IntegerField(),
        ),
    ]
