# Generated by Django 2.0.5 on 2018-11-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0009_discount_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='contact_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='useruseddiscount',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
