# Generated by Django 2.0.5 on 2018-11-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0010_auto_20181101_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiscount',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
