# Generated by Django 2.1.3 on 2018-11-14 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0011_userdiscount_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruseddiscount',
            name='cafe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_discounts', to='discounts.Cafe'),
        ),
        migrations.AlterField(
            model_name='useruseddiscount',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_used_discounts', to='discounts.Discount'),
        ),
    ]
