# Generated by Django 2.1.3 on 2019-02-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0011_auto_20190211_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiscount',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
