# Generated by Django 2.1.3 on 2018-11-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0012_auto_20181114_1920'),
        ('discounts', '0008_auto_20181114_1936'),
    ]

    operations = [
    ]
