# Generated by Django 2.1.3 on 2019-02-20 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0012_auto_20190211_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
