# Generated by Django 2.1.3 on 2019-02-22 06:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discounts', '0014_auto_20190220_0945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserUsedDiscount',
            new_name='UserDiscountArchive',
        ),
    ]
