# Generated by Django 2.2.3 on 2020-03-05 09:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultants', '0002_consultantprofile_user'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePackageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='StorePackageDetailPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='StorePackageDetailPhaseThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('store_package_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.StorePackageDetail')),
                ('store_package_detail_phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.StorePackageDetailPhase')),
            ],
        ),
        migrations.AddField(
            model_name='storepackagedetail',
            name='store_package_phases',
            field=models.ManyToManyField(through='packages.StorePackageDetailPhaseThrough', to='packages.StorePackageDetailPhase'),
        ),
        migrations.CreateModel(
            name='StorePackage',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.Product')),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultants.ConsultantProfile')),
                ('store_package_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.StorePackageDetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('store.product',),
        ),
    ]
