# Generated by Django 2.1.3 on 2019-02-08 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('teacher', models.CharField(default=None, max_length=200)),
                ('number_of_views', models.IntegerField(default=0, help_text='لطفا مقدار را عوض نکنید ( به جز در مواقع نیاز شدید و باگ)', verbose_name='تعداد بازدید')),
                ('booklet_content', models.FileField(upload_to='website/booklet_content')),
                ('booklet_image', models.ImageField(upload_to='website/booklet_images')),
            ],
        ),
        migrations.CreateModel(
            name='BookletField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(help_text='Lower case', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookletTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sample: برنامه\u200cنویسی پیشرفته', max_length=120)),
                ('slug', models.SlugField(help_text='Lower case |Sample: advanced-programming', null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='booklet.BookletField')),
            ],
        ),
        migrations.AddField(
            model_name='booklet',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklets', to='booklet.BookletTopic'),
        ),
    ]
