# Generated by Django 2.1.3 on 2019-02-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklet',
            name='information',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
