# Generated by Django 2.1.3 on 2019-02-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0002_booklet_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklettopic',
            name='slug',
            field=models.SlugField(help_text='Lower case |Sample: advanced-programming'),
        ),
    ]
