# Generated by Django 2.1.3 on 2019-02-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0003_auto_20190209_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklet',
            name='number_of_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booklet',
            name='number_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
