# Generated by Django 2.1.3 on 2019-02-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0005_auto_20190209_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklet',
            name='number_of_dislikes',
        ),
    ]
