# Generated by Django 2.1.3 on 2019-02-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0006_remove_booklet_number_of_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklet',
            name='writer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='booklet',
            name='year',
            field=models.IntegerField(blank=True, help_text='In 1997 format.', null=True),
        ),
    ]
