# Generated by Django 2.1.3 on 2019-02-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0007_auto_20190215_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('slug', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='booklet',
            name='year',
            field=models.IntegerField(blank=True, help_text='In 1397 format.', null=True),
        ),
    ]
