# Generated by Django 2.1.3 on 2019-02-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0008_auto_20190215_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=2000),
        ),
    ]
