# Generated by Django 2.1.3 on 2019-02-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0009_auto_20190215_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklet',
            name='tags',
            field=models.CharField(blank=True, help_text='به این صورت وارد کنید : <br/>جزوه ریاضی|بهترین جزوه عالم|جزوه بخون حالشو ببر', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text='If you are adding this tag for first time, leave this field blank.Only change this field if there is a mistake or for other purposes ...', max_length=2000, null=True),
        ),
    ]
