# Generated by Django 2.1.3 on 2019-02-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0010_auto_20190215_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklet',
            name='tags_str',
            field=models.CharField(blank=True, help_text='به این صورت وارد کنید : <br/>جزوه ریاضی|بهترین جزوه عالم|جزوه بخون حالشو ببر', max_length=2000, null=True),
        ),
        migrations.RemoveField(
            model_name='booklet',
            name='tags',
        ),
        migrations.AddField(
            model_name='booklet',
            name='tags',
            field=models.ManyToManyField(to='booklet.Tag'),
        ),
    ]
