# Generated by Django 2.1.3 on 2019-02-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0011_auto_20190215_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='booklet.Tag'),
        ),
    ]
