# Generated by Django 2.1.3 on 2019-02-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0013_auto_20190215_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text="Don't change this if you are creating new booklet. Only change this if it is necessary.", null=True, related_name='booklets', to='booklet.Tag'),
        ),
    ]
