# Generated by Django 2.1.3 on 2019-02-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0014_auto_20190215_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text="Don't change this if you are creating new booklet. Only change this if it is necessary.", related_name='booklets', to='booklet.Tag'),
        ),
    ]
