# Generated by Django 2.1.3 on 2019-02-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0015_auto_20190221_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklet',
            name='information',
        ),
        migrations.AddField(
            model_name='booklettopic',
            name='information',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
