# Generated by Django 2.1.3 on 2019-02-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0016_auto_20190225_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookletfield',
            name='slug',
            field=models.SlugField(help_text='Lower case', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booklettopic',
            name='slug',
            field=models.SlugField(help_text='Lower case |Sample: advanced-programming', unique=True),
        ),
    ]
