# Generated by Django 2.1.3 on 2019-02-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0017_auto_20190225_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklet',
            name='number_of_views',
        ),
        migrations.RemoveField(
            model_name='booklet',
            name='tags_str',
        ),
        migrations.AlterField(
            model_name='booklet',
            name='booklet_content',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='booklet',
            name='booklet_image',
            field=models.URLField(),
        ),
    ]
