# Generated by Django 2.1.3 on 2019-02-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0018_auto_20190225_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='teacher',
            field=models.CharField(max_length=200),
        ),
    ]
