# Generated by Django 2.1.3 on 2019-02-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0019_auto_20190225_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='booklet_image',
            field=models.ImageField(upload_to='pictures/booklets'),
        ),
    ]
