# Generated by Django 2.1.3 on 2019-02-27 17:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booklet', '0021_auto_20190227_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDownload',
            new_name='BookletDownload',
        ),
    ]
