# Generated by Django 2.1.3 on 2019-03-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0022_auto_20190227_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='booklet_image',
            field=models.URLField(),
        ),
    ]
