# Generated by Django 2.1.3 on 2019-03-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0024_auto_20190301_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='booklet_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
