# Generated by Django 2.1.3 on 2019-03-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0026_auto_20190301_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklettopic',
            name='information',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
