# Generated by Django 2.1.3 on 2019-03-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0027_auto_20190302_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklettopic',
            name='information',
            field=models.TextField(blank=True, help_text='Can be empty', max_length=10000, null=True),
        ),
    ]
