# Generated by Django 2.1.3 on 2019-03-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0028_auto_20190303_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='number_of_pages',
            field=models.IntegerField(blank=True, default=0, help_text='حتما دقیق نوشته شود', null=True),
        ),
        migrations.AlterField(
            model_name='booklet',
            name='teacher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
