# Generated by Django 2.1.3 on 2019-03-04 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0029_auto_20190304_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookletdownload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklet_downloads', to=settings.AUTH_USER_MODEL),
        ),
    ]
