# Generated by Django 2.2.3 on 2020-02-21 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_soldproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldtimeslotsale',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='soldtimeslotsale',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='soldtimeslotsale',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='soldtimeslotsale',
            name='sold_to',
        ),
        migrations.RemoveField(
            model_name='soldtimeslotsale',
            name='start_time',
        ),
        migrations.AddField(
            model_name='soldtimeslotsale',
            name='soldproduct_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.SoldProduct'),
            preserve_default=False,
        ),
    ]
