# Generated by Django 2.2.3 on 2019-07-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190722_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldtimeslotsale',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
