# Generated by Django 2.2.3 on 2020-03-08 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_consultantprofile_user'),
        ('store', '0002_auto_20200306_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantAcceptSoldProductRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultants.ConsultantProfile')),
                ('sold_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.SoldProduct')),
            ],
            options={
                'unique_together': {('sold_product', 'consultant')},
            },
        ),
    ]
