# Generated by Django 2.2.3 on 2020-02-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200221_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
