# Generated by Django 2.2.3 on 2020-03-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_consultantacceptsoldproductrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
