# Generated by Django 2.2.3 on 2019-09-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_soldtimeslotsale_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldtimeslotsale',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='timeslotsale',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
