# Generated by Django 2.2.3 on 2020-03-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200323_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultantAcceptSoldProductRequest',
        ),
    ]
