# Generated by Django 2.2.3 on 2020-05-20 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_delete_consultantacceptsoldproductrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproduct',
            name='sold_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
