# Generated by Django 2.2.3 on 2019-08-09 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_cart_discount_percent'),
        ('discounts', '0003_consultantdiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartConsultantDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart')),
                ('consultant_discount', models.ManyToManyField(to='discounts.ConsultantDiscount')),
            ],
        ),
    ]
