# Generated by Django 2.2.3 on 2019-08-09 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0006_auto_20190809_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartconsultantdiscount',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart'),
        ),
    ]
