# Generated by Django 2.2.3 on 2020-02-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200214_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='time_slot_sales',
            new_name='products',
        ),
    ]
