# Generated by Django 2.2.3 on 2020-02-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_soldorder'),
        ('carts', '0002_auto_20200212_0613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoldCart',
        ),
    ]
