# Generated by Django 2.2.3 on 2019-08-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='time_slot',
            new_name='sold_time_slot',
        ),
        migrations.AlterField(
            model_name='room',
            name='consultant_login_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_login_url',
            field=models.URLField(blank=True),
        ),
    ]
