# Generated by Django 2.2.3 on 2019-08-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochats', '0003_auto_20190816_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='user1_id',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='user2_id',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='consultant_login_url',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_login_url',
            field=models.URLField(max_length=1024),
        ),
    ]
