# Generated by Django 2.1.3 on 2019-02-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190203_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post title', 'verbose_name_plural': 'Post titles'},
        ),
    ]
