# Generated by Django 2.1.3 on 2019-02-04 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_usercomment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commnets', to='blog.Post'),
        ),
    ]
