# Generated by Django 2.1.3 on 2019-02-04 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=400)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_comment', to='blog.UserComment')),
            ],
        ),
    ]
