# Generated by Django 2.1.3 on 2019-02-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_admincomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincomment',
            name='user_comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_comment', to='blog.UserComment'),
        ),
    ]
