# Generated by Django 2.1.3 on 2019-02-05 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190204_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostTag',
        ),
    ]
