# Generated by Django 2.1.3 on 2019-02-08 07:34

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_hellomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_main_image',
            field=models.ImageField(default='', upload_to=blog.models.upload_post_image),
        ),
    ]
