# Generated by Django 2.1.3 on 2019-02-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_post_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aparat_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
