# Generated by Django 2.1.3 on 2019-02-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_youtube_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelloModel',
        ),
        migrations.AlterField(
            model_name='post',
            name='aparat_link',
            field=models.URLField(blank=True, help_text="Don't fill this if this post has no video.\nSapmle: https://www.aparat.com/v/4Y7PV ", null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='youtube_link',
            field=models.URLField(blank=True, help_text="Don't fill this if this post has no video.\nSample: https://www.youtube.com/watch?v=h1QkGnI4P6g ", null=True),
        ),
    ]
