# Generated by Django 2.1.3 on 2019-02-08 13:39

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190208_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamp_jalali',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True),
        ),
    ]
