# Generated by Django 2.1.3 on 2019-02-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Q&A', 'Question and Answer'), ('interview', 'Interview')], default='Q&A', max_length=50),
        ),
    ]
