# Generated by Django 2.1.3 on 2019-02-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20190209_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='questions',
            field=models.ManyToManyField(to='blog.PostQuestion'),
        ),
    ]
