# Generated by Django 2.1.3 on 2019-02-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_post_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostQuestionAndAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='postquestion',
            name='answer',
        ),
        migrations.AlterField(
            model_name='post',
            name='questions',
            field=models.ManyToManyField(to='blog.PostQuestionAndAnswer'),
        ),
        migrations.DeleteModel(
            name='PostQuestion',
        ),
        migrations.DeleteModel(
            name='PostQuestionAnswer',
        ),
    ]
