# Generated by Django 2.1.3 on 2019-02-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20190209_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='postquestionandanswer',
            name='answer',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='postquestionandanswer',
            name='question',
            field=models.TextField(default=None),
        ),
    ]
