# Generated by Django 2.1.3 on 2019-02-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20190209_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='questions',
            new_name='questions_and_answers',
        ),
    ]
