# Generated by Django 2.1.3 on 2019-02-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20190209_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='questions_and_answers',
            field=models.ManyToManyField(blank=True, null=True, to='blog.PostQuestionAndAnswer'),
        ),
    ]
