# Generated by Django 2.1.3 on 2019-02-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20190209_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='questions_and_answers',
            field=models.ManyToManyField(blank=True, to='blog.PostQuestionAndAnswer'),
        ),
    ]
