# Generated by Django 2.1.3 on 2019-03-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20190227_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_main_image',
            field=models.URLField(),
        ),
    ]
