# Generated by Django 2.1.3 on 2019-03-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20190301_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_main_image',
            field=models.ImageField(null=True, upload_to='aaa'),
        ),
    ]
