# Generated by Django 2.1.3 on 2019-03-01 05:55

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20190301_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_main_image',
            field=models.ImageField(null=True, upload_to=blog.models.upload_post_image),
        ),
    ]
