# Generated by Django 2.2.3 on 2020-02-29 09:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sNeeds.apps.discounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotSaleNumberDiscount',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('discount', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('code', sNeeds.apps.discounts.models.CICharField(max_length=128, unique=True)),
                ('consultants', models.ManyToManyField(to='consultants.ConsultantProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CartConsultantDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cart')),
                ('consultant_discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.ConsultantDiscount')),
            ],
            options={
                'unique_together': {('cart', 'consultant_discount')},
            },
        ),
    ]
