# Generated by Django 2.2.3 on 2020-03-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200301_1251'),
        ('consultants', '0003_auto_20200309_1356'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsultantDiscount',
            new_name='Discount',
        ),
    ]
