# Generated by Django 2.2.3 on 2020-02-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0001_initial'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantdiscount',
            name='consultant',
        ),
        migrations.AddField(
            model_name='consultantdiscount',
            name='consultants',
            field=models.ManyToManyField(to='customAuth.ConsultantProfile'),
        ),
    ]
