# Generated by Django 2.2.3 on 2019-08-09 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20190730_0406'),
        ('discounts', '0002_auto_20190802_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('consultant', models.ManyToManyField(to='account.ConsultantProfile')),
            ],
        ),
    ]
