# Generated by Django 2.2.3 on 2020-02-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_auto_20200215_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantdiscount',
            name='active',
        ),
    ]
