# Generated by Django 2.2.3 on 2020-03-14 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200229_0949'),
        ('discounts', '0002_auto_20200314_1113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartConsultantDiscount',
            new_name='CartDiscount',
        ),
    ]
