# Generated by Django 2.2.3 on 2020-02-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_remove_consultantdiscount_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartconsultantdiscount',
            name='consultant_discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.ConsultantDiscount'),
        ),
    ]
