# Generated by Django 2.2.3 on 2020-03-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200229_0949'),
        ('discounts', '0003_auto_20200314_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdiscount',
            old_name='consultant_discount',
            new_name='discount',
        ),
        migrations.AlterUniqueTogether(
            name='cartdiscount',
            unique_together={('cart', 'discount')},
        ),
    ]
