# Generated by Django 2.2.3 on 2019-08-09 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_auto_20190809_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartconsultantdiscount',
            name='consultant_discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discounts.ConsultantDiscount'),
        ),
    ]
