# Generated by Django 2.2.3 on 2020-03-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0006_auto_20200318_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='amount',
        ),
    ]
