# Generated by Django 2.2.3 on 2020-03-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0007_remove_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
