# Generated by Django 2.2.3 on 2019-08-09 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20190809_0352'),
        ('discounts', '0008_auto_20190809_0402'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartconsultantdiscount',
            unique_together={('cart', 'consultant_discount')},
        ),
    ]
