# Generated by Django 2.2.3 on 2020-03-24 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discounts', '0009_auto_20200319_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='creator',
            field=models.CharField(choices=[('C', 'Consultant'), ('A', 'Admin')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='discount',
            name='use_limit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
