# Generated by Django 2.2.3 on 2019-08-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0009_auto_20190809_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantdiscount',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultantdiscount',
            name='code',
            field=models.CharField(default='ee', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
