# Generated by Django 2.2.3 on 2020-03-25 19:24

from django.db import migrations
import sNeeds.apps.discounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0010_auto_20200324_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=sNeeds.apps.discounts.models.CICharField(blank=True, help_text='Leave this field blank, this will populate automatically.', max_length=128, unique=True),
        ),
    ]
