# Generated by Django 2.2.3 on 2019-09-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0012_auto_20190912_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantdiscount',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
