# Generated by Django 2.2.3 on 2020-04-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0013_auto_20200326_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='creator',
            field=models.CharField(choices=[('consultant', 'Consultant'), ('admin', 'Admin')], default='admin', max_length=1),
        ),
    ]
