# Generated by Django 2.2.3 on 2019-09-12 13:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0013_consultantdiscount_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantdiscount',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 13, 13, 1, 483353)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultantdiscount',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
