# Generated by Django 2.2.3 on 2019-09-12 17:28

from django.db import migrations, models
import django.db.models.deletion
import sNeeds.apps.discounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0014_auto_20190912_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartconsultantdiscount',
            name='consultant_discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.ConsultantDiscount', validators=[sNeeds.apps.discounts.models.validate_consultant_discount]),
        ),
    ]
