# Generated by Django 2.2.3 on 2020-05-21 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0015_auto_20200405_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
