# Generated by Django 2.2.3 on 2019-09-19 07:30

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0015_auto_20190912_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantdiscount',
            name='code',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=128, unique=True),
        ),
    ]
