# Generated by Django 2.2.3 on 2019-09-29 02:18

from django.db import migrations, models
import sNeeds.apps.discounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0016_auto_20190919_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantdiscount',
            name='code',
            field=models.CharField(max_length=128, validators=[sNeeds.apps.discounts.models.uniqueness_validator]),
        ),
    ]
