# Generated by Django 2.2.3 on 2019-09-29 03:50

from django.db import migrations
import sNeeds.apps.discounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0016_auto_20190919_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantdiscount',
            name='code',
            field=sNeeds.apps.discounts.models.CICharField(max_length=128, unique=True),
        ),
    ]
