# Generated by Django 2.2.3 on 2020-03-21 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0005_auto_20200308_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.Product')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='SoldBasicProduct',
            fields=[
                ('soldproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.SoldProduct')),
                ('basic_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicProducts.BasicProduct')),
            ],
            bases=('store.soldproduct',),
        ),
    ]
