# Generated by Django 2.2.3 on 2020-06-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicProducts', '0004_auto_20200618_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomlink',
            name='product',
        ),
        migrations.AddField(
            model_name='classroomlink',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='basicProducts.ClassProduct'),
        ),
        migrations.AddField(
            model_name='webinarroomlink',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='basicProducts.WebinarProduct'),
        ),
        migrations.AlterField(
            model_name='roomlink',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
