# Generated by Django 2.2.3 on 2020-06-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicProducts', '0006_auto_20200624_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='classproduct',
            name='type',
            field=models.CharField(default='class', max_length=10),
        ),
        migrations.AddField(
            model_name='webinarproduct',
            name='type',
            field=models.CharField(default='webinar', max_length=10),
        ),
    ]
