# Generated by Django 2.2.3 on 2020-06-24 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicProducts', '0007_auto_20200624_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlink',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downlaodlink', to='basicProducts.ClassWebinar'),
        ),
    ]
