# Generated by Django 2.2.3 on 2020-06-24 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicProducts', '0008_auto_20200624_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldbasicproduct',
            name='basic_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='basicproducts_soldbasicproduct', to='basicProducts.BasicProduct'),
        ),
    ]
