# Generated by Django 2.2.3 on 2020-06-24 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicProducts', '0009_auto_20200624_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlink',
            name='class_webinar_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='basicProducts.ClassWebinar'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='roomlink',
            unique_together={('class_webinar_product', 'user')},
        ),
    ]
