# Generated by Django 2.2.3 on 2020-06-24 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicProducts', '0010_auto_20200625_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomlink',
            name='class_webinar_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicProducts.BasicProduct'),
        ),
    ]
