# Generated by Django 2.2.3 on 2020-06-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicProducts', '0011_auto_20200625_0037'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomlink',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='roomlink',
            name='class_webinar_product',
        ),
    ]
