# Generated by Django 2.2.3 on 2020-06-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicProducts', '0012_auto_20200625_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldbasicproduct',
            name='basic_product',
        ),
        migrations.AddField(
            model_name='soldclassproduct',
            name='class_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basicProducts.ClassProduct'),
        ),
        migrations.AddField(
            model_name='soldwebinarproduct',
            name='webinar_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basicProducts.WebinarProduct'),
        ),
    ]
