# Generated by Django 2.2.3 on 2019-08-30 15:36

from django.db import migrations, models
import sNeeds.apps.userfiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('userfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to=sNeeds.apps.userfiles.models.get_file_upload_path),
        ),
    ]
