# Generated by Django 2.2.3 on 2020-03-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldstorepackage',
            old_name='store_package_detail',
            new_name='store_package',
        ),
    ]
