# Generated by Django 2.2.3 on 2020-03-22 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200322_1810'),
        ('storePackages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldStorePaidPackagePhase',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.Product')),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='SoldStoreUnpaidPackagePhase',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.Product')),
            ],
            bases=('store.product',),
        ),
        migrations.DeleteModel(
            name='SoldStorePackagePhase',
        ),
    ]
