# Generated by Django 2.2.3 on 2020-03-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storepackagedetailphasethrough',
            options={'ordering': ['order']},
        ),
    ]
