# Generated by Django 2.2.3 on 2020-03-22 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200322_1810'),
        ('storePackages', '0002_auto_20200322_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soldstorepaidpackagephase',
            options={'ordering': ['phase_number']},
        ),
        migrations.AlterModelOptions(
            name='soldstoreunpaidpackagephase',
            options={'ordering': ['phase_number']},
        ),
        migrations.RemoveField(
            model_name='soldstoreunpaidpackagephase',
            name='product_ptr',
        ),
        migrations.AddField(
            model_name='soldstorepaidpackagephase',
            name='consultant_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soldstorepaidpackagephase',
            name='detailed_title',
            field=models.CharField(default=None, help_text='This field is for ourselves, Feel free to add details.', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldstorepaidpackagephase',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soldstorepaidpackagephase',
            name='phase_number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldstorepaidpackagephase',
            name='sold_store_package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storePackages.SoldStorePackage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldstorepaidpackagephase',
            name='status',
            field=models.CharField(choices=[('not_started', 'شروع نشده'), ('pay_to_start', 'نیازمند پرداخت برای شروع'), ('in_progress', 'در حال انجام'), ('done', 'انجام شده')], default='not_started', max_length=128),
        ),
        migrations.AddField(
            model_name='soldstorepaidpackagephase',
            name='title',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldstoreunpaidpackagephase',
            name='consultant_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soldstoreunpaidpackagephase',
            name='detailed_title',
            field=models.CharField(default=None, help_text='This field is for ourselves, Feel free to add details.', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldstoreunpaidpackagephase',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soldstoreunpaidpackagephase',
            name='phase_number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldstoreunpaidpackagephase',
            name='sold_store_package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storePackages.SoldStorePackage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldstoreunpaidpackagephase',
            name='soldproduct_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.SoldProduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldstoreunpaidpackagephase',
            name='status',
            field=models.CharField(choices=[('not_started', 'شروع نشده'), ('pay_to_start', 'نیازمند پرداخت برای شروع'), ('in_progress', 'در حال انجام'), ('done', 'انجام شده')], default='not_started', max_length=128),
        ),
        migrations.AddField(
            model_name='soldstoreunpaidpackagephase',
            name='title',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
    ]
