# Generated by Django 2.2.3 on 2020-03-23 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200322_1810'),
        ('storePackages', '0002_auto_20200322_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldstorepaidpackagephase',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='soldstoreunpaidpackagephase',
            name='soldproduct_ptr',
        ),
        migrations.AddField(
            model_name='soldstorepaidpackagephase',
            name='soldproduct_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.SoldProduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldstoreunpaidpackagephase',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.Product'),
            preserve_default=False,
        ),
    ]
