# Generated by Django 2.2.3 on 2020-03-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0002_auto_20200306_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepackagedetail',
            name='detailed_title',
            field=models.CharField(default='temp', help_text='Used for ourselves, feel free to add details.', max_length=1024),
            preserve_default=False,
        ),
    ]
