# Generated by Django 2.2.3 on 2020-03-06 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('storePackages', '0002_auto_20200306_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storepackagephasethrough',
            name='id',
        ),
        migrations.AddField(
            model_name='storepackagephasethrough',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.Product'),
            preserve_default=False,
        ),
    ]
