# Generated by Django 2.2.3 on 2020-03-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0003_auto_20200306_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storepackagephasethrough',
            name='product_ptr',
        ),
        migrations.AddField(
            model_name='storepackagephasethrough',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
