# Generated by Django 2.2.3 on 2020-03-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0003_auto_20200323_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldstoreunpaidpackagephase',
            name='consultant_done',
        ),
    ]
