# Generated by Django 2.2.3 on 2020-03-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0003_storepackagedetail_detailed_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storepackagedetail',
            name='detailed_title',
        ),
    ]
