# Generated by Django 2.2.3 on 2020-03-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0004_remove_storepackagedetail_detailed_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepackagedetailphase',
            name='detailed_title',
            field=models.CharField(default='test', help_text='This field is for ourselves, Feel free to add details.', max_length=1024),
            preserve_default=False,
        ),
    ]
