# Generated by Django 2.2.3 on 2020-03-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0005_storepackagedetailphase_detailed_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storepackagedetailphasethrough',
            unique_together={('store_package_detail', 'store_package_detail_phase', 'order')},
        ),
    ]
