# Generated by Django 2.2.3 on 2020-03-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0005_auto_20200306_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storepackagephasethrough',
            options={'ordering': ['phase_number']},
        ),
        migrations.RenameField(
            model_name='storepackagephasethrough',
            old_name='order',
            new_name='phase_number',
        ),
        migrations.AlterField(
            model_name='storepackage',
            name='store_package_phases',
            field=models.ManyToManyField(related_name='store_packages', through='storePackages.StorePackagePhaseThrough', to='storePackages.StorePackagePhase'),
        ),
        migrations.AlterUniqueTogether(
            name='storepackagephasethrough',
            unique_together={('store_package', 'store_package_phase'), ('store_package', 'phase_number')},
        ),
    ]
