# Generated by Django 2.2.3 on 2020-03-26 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0006_auto_20200325_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldstorepackage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldstorepackage',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
