# Generated by Django 2.2.3 on 2020-03-06 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0006_auto_20200306_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storepackagedetailphase',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
