# Generated by Django 2.2.3 on 2020-03-29 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('storePackages', '0007_auto_20200326_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldStorePackagePhaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('not_started', 'شروع نشده'), ('in_progress', 'در حال انجام'), ('done', 'انجام شد'), ('succeeded', 'موفقیت در گرفتن نتیجه'), ('failed', 'عدم موفقیت در گرفتن نتیجه'), ('canceled', 'موفقیت در گرفتن نتیجه')], max_length=1024)),
                ('object_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
