# Generated by Django 2.2.3 on 2020-03-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200301_1251'),
        ('store', '0005_auto_20200308_0756'),
        ('storePackages', '0007_soldstorepackagephase_unpaidstorepackagephase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unpaidstorepackagephase',
            name='sold_store_package',
        ),
        migrations.RemoveField(
            model_name='soldstorepackage',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='soldstorepackage',
            name='store_package',
        ),
        migrations.DeleteModel(
            name='SoldStorePackagePhase',
        ),
        migrations.DeleteModel(
            name='UnpaidStorePackagePhase',
        ),
    ]
