# Generated by Django 2.2.3 on 2020-03-06 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0007_auto_20200306_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storepackagedetailphasethrough',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='storepackagedetailphasethrough',
            unique_together={('store_package_detail', 'order'), ('store_package_detail', 'store_package_detail_phase')},
        ),
    ]
