# Generated by Django 2.2.3 on 2020-03-08 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_consultantprofile_user'),
        ('storePackages', '0008_auto_20200308_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldstorepackage',
            name='consultant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultants.ConsultantProfile'),
        ),
    ]
