# Generated by Django 2.2.3 on 2020-03-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0008_soldstorepackagephasedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldstorepackagephasedetail',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'storePackages'), ('model', 'soldstorepaidpackagephase')), models.Q(('app_label', 'storePackages'), ('model', 'soldstoreunpaidpackagephase')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
