# Generated by Django 2.2.3 on 2020-03-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0008_auto_20200306_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepackage',
            name='slug',
            field=models.SlugField(default='temp', unique=True),
            preserve_default=False,
        ),
    ]
