# Generated by Django 2.2.3 on 2020-03-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0009_soldstorepackage_consultant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldstorepackage',
            name='soldproduct_ptr',
        ),
    ]
