# Generated by Django 2.2.3 on 2020-03-30 06:28

from django.db import migrations, models
import sNeeds.apps.storePackages.models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0009_auto_20200329_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldstorepackagephasedetail',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=sNeeds.apps.storePackages.models.get_sold_store_package_phase_detail_file_upload_path),
        ),
        migrations.AlterField(
            model_name='soldstorepackagephasedetail',
            name='status',
            field=models.CharField(choices=[('in_progress', 'در حال انجام'), ('done', 'انجام شد'), ('finished', 'دریافت نتیجه'), ('failed', 'عدم موفقیت در گرفتن نتیجه'), ('canceled', 'لغو شد')], max_length=1024),
        ),
    ]
