# Generated by Django 2.2.3 on 2020-03-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200308_0756'),
        ('orders', '0002_auto_20200301_1251'),
        ('storePackages', '0010_auto_20200308_1001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoldStorePackage',
        ),
    ]
