# Generated by Django 2.2.3 on 2020-03-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0010_auto_20200330_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soldstorepackagephasedetail',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='soldstorepackagephasedetail',
            name='status',
            field=models.CharField(choices=[('in_progress', 'در حال انجام'), ('done', 'انجام شد'), ('finished', 'دریافت نتیجه'), ('pending_user_data', 'دریافت اطلاعات کاربر')], max_length=1024),
        ),
    ]
