# Generated by Django 2.2.3 on 2020-03-08 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_consultantprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storePackages', '0011_delete_soldstorepackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldStorePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultants.ConsultantProfile')),
                ('sold_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
