# Generated by Django 2.2.3 on 2020-06-20 17:40

from django.db import migrations, models
import sNeeds.apps.storePackages.models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0011_auto_20200330_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepackage',
            name='image',
            field=models.ImageField(null=True, upload_to=sNeeds.apps.storePackages.models.get_store_package_image_upload_path),
        ),
    ]
