# Generated by Django 2.2.3 on 2020-03-08 10:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200308_0756'),
        ('storePackages', '0012_soldstorepackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnpaidStorePackagePhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('detailed_title', models.CharField(help_text='This field is for ourselves, Feel free to add details.', max_length=1024)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sold_store_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storePackages.SoldStorePackage')),
            ],
        ),
        migrations.CreateModel(
            name='SoldStorePackagePhase',
            fields=[
                ('soldproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.SoldProduct')),
                ('title', models.CharField(max_length=1024)),
                ('detailed_title', models.CharField(help_text='This field is for ourselves, Feel free to add details.', max_length=1024)),
                ('sold_store_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storePackages.SoldStorePackage')),
            ],
            bases=('store.soldproduct',),
        ),
    ]
