# Generated by Django 2.2.3 on 2020-06-20 19:15

import ckeditor.fields
from django.db import migrations, models
import sNeeds.apps.storePackages.models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0013_auto_20200620_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldstorepaidpackagephase',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soldstoreunpaidpackagephase',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storepackagephase',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storepackage',
            name='image',
            field=models.ImageField(null=True, upload_to=sNeeds.apps.storePackages.models.get_store_package_image_upload_path),
        ),
    ]
