# Generated by Django 2.2.3 on 2020-03-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0013_soldstorepackagephase_unpaidstorepackagephase'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldstorepackage',
            name='store_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storePackages.StorePackage'),
        ),
    ]
