# Generated by Django 2.2.3 on 2020-06-21 09:48

from django.db import migrations, models
import sNeeds.apps.storePackages.models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0014_auto_20200620_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePackagePhaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='soldstorepackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sNeeds.apps.storePackages.models.get_sold_store_package_image_upload_path),
        ),
        migrations.AlterField(
            model_name='storepackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sNeeds.apps.storePackages.models.get_store_package_image_upload_path),
        ),
        migrations.AddField(
            model_name='storepackagephase',
            name='phase_details',
            field=models.ManyToManyField(to='storePackages.StorePackagePhaseDetail'),
        ),
    ]
