# Generated by Django 2.2.3 on 2020-03-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0014_soldstorepackage_store_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepackage',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
