# Generated by Django 2.2.3 on 2020-06-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0015_auto_20200621_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldstorepackagephasedetail',
            name='status',
            field=models.CharField(choices=[('not_started', 'شروع نشده'), ('in_progress', 'در حال انجام'), ('done', 'انجام شد'), ('finished', 'دریافت نتیجه'), ('pending_user_data', 'دریافت اطلاعات کاربر')], max_length=1024),
        ),
    ]
