# Generated by Django 2.2.3 on 2020-06-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0016_auto_20200621_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldstorepaidpackagephase',
            name='detailed_title',
        ),
        migrations.RemoveField(
            model_name='soldstoreunpaidpackagephase',
            name='detailed_title',
        ),
        migrations.RemoveField(
            model_name='storepackagephase',
            name='detailed_title',
        ),
        migrations.AlterField(
            model_name='storepackagephase',
            name='phase_details',
            field=models.ManyToManyField(blank=True, null=True, to='storePackages.StorePackagePhaseDetail'),
        ),
    ]
