# Generated by Django 2.2.3 on 2020-03-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200314_1128'),
        ('store', '0005_auto_20200308_0756'),
        ('storePackages', '0016_auto_20200316_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoldStorePackagePhase',
        ),
    ]
