# Generated by Django 2.2.3 on 2020-03-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0017_delete_soldstorepackagephase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnpaidStorePackagePhase',
            new_name='SoldStorePackagePhase',
        ),
    ]
