# Generated by Django 2.2.3 on 2020-06-21 13:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0018_auto_20200621_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldstorepackagephasedetail',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storepackagephasedetail',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
