# Generated by Django 2.2.3 on 2020-03-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0018_auto_20200316_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldstorepackagephase',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
