# Generated by Django 2.2.3 on 2020-06-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0019_auto_20200621_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldstorepackagephasedetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soldstorepaidpackagephase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soldstoreunpaidpackagephase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storepackagephase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storepackagephasedetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
