# Generated by Django 2.2.3 on 2020-03-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0019_soldstorepackagephase_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soldstorepackagephase',
            options={'ordering': ['phase_number']},
        ),
        migrations.RemoveField(
            model_name='soldstorepackagephase',
            name='sold_store_package',
        ),
        migrations.AddField(
            model_name='soldstorepackage',
            name='sold_store_package_phases',
            field=models.ManyToManyField(to='storePackages.SoldStorePackagePhase'),
        ),
        migrations.AddField(
            model_name='soldstorepackagephase',
            name='phase_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
