# Generated by Django 2.2.3 on 2020-03-19 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200308_0756'),
        ('storePackages', '0020_auto_20200316_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldstorepackage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='soldstorepackage',
            name='sold_to',
        ),
        migrations.AddField(
            model_name='soldstorepackage',
            name='soldproduct_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.SoldProduct'),
            preserve_default=False,
        ),
    ]
