# Generated by Django 2.2.3 on 2020-03-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0021_auto_20200319_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldstorepackage',
            name='store_package',
        ),
        migrations.AddField(
            model_name='soldstorepackage',
            name='title',
            field=models.CharField(default='temp', max_length=1024),
            preserve_default=False,
        ),
    ]
