# Generated by Django 2.2.3 on 2020-03-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0022_auto_20200319_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldstorepackage',
            name='total_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
