# Generated by Django 2.2.3 on 2020-03-19 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0023_soldstorepackage_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldstorepackage',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultants.ConsultantProfile'),
        ),
    ]
