# Generated by Django 2.2.3 on 2020-03-22 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0025_auto_20200322_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldstorepackagephase',
            name='sold_store_package',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='sold_store_package_phases', to='storePackages.SoldStorePackage'),
            preserve_default=False,
        ),
    ]
