# Generated by Django 2.2.3 on 2019-08-17 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sNeeds.apps.tweet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=sNeeds.apps.tweet.models.path_for_uploading_file)),
                ('text', models.CharField(max_length=256)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
