# Generated by Django 2.2.3 on 2019-08-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetmodel',
            old_name='file',
            new_name='info',
        ),
    ]
