# Generated by Django 2.2.3 on 2019-08-13 18:10

from django.db import migrations, models
import tweet.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20190813_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetmodel',
            name='info',
        ),
        migrations.AddField(
            model_name='tweetmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=tweet.models.path_for_uploading_file),
        ),
    ]
