# Generated by Django 2.2.3 on 2019-07-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0004_auto_20190716_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='created', max_length=256)),
                ('total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.Cart')),
            ],
        ),
    ]
