# Generated by Django 2.2.3 on 2019-07-06 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190706_0359'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslotsale',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_sales_as_buyer', to='account.ConsultantProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeslotsale',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_sales_as_consultant', to='account.ConsultantProfile'),
        ),
    ]
