# Generated by Django 2.2.3 on 2019-07-06 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190706_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslotsale',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_sales_as_buyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
