# Generated by Django 2.2.3 on 2019-07-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190706_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslotsale',
            name='buyer',
        ),
        migrations.AlterField(
            model_name='timeslotsale',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_sales', to='account.ConsultantProfile'),
        ),
    ]
