# Generated by Django 2.2.3 on 2020-02-29 09:49

from django.db import migrations, models
import sNeeds.apps.account.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(upload_to=sNeeds.apps.consultants.models.get_consultant_image_path)),
                ('aparat_link', models.URLField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to=sNeeds.apps.consultants.models.get_consultant_resume_path)),
                ('slug', models.SlugField(help_text='lowercase pls', unique=True)),
                ('active', models.BooleanField(default=True)),
                ('time_slot_price', models.PositiveIntegerField()),
                ('rate', models.FloatField(blank=True, default=None, null=True)),
                ('countries', models.ManyToManyField(blank=True, to='account.Country')),
                ('field_of_studies', models.ManyToManyField(blank=True, to='account.FieldOfStudy')),
                ('universities', models.ManyToManyField(blank=True, to='account.University')),
            ],
        ),
    ]
