# Generated by Django 2.2.3 on 2020-03-09 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_consultantprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
