# Generated by Django 2.2.3 on 2020-03-26 19:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0003_auto_20200309_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='bio',
            field=tinymce.models.HTMLField(default='default'),
        ),
    ]
