# Generated by Django 2.2.3 on 2020-04-11 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200405_1437'),
        ('consultants', '0004_auto_20200326_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='universities',
            field=models.ManyToManyField(blank=True, related_name='consultants', to='account.University'),
        ),
        migrations.CreateModel(
            name='StudyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, choices=[('college', 'College'), ('associate', 'Associate'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('doctoral', 'Doctoral'), ('post_doctoral', 'Post Doctoral')], max_length=64)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultants.ConsultantProfile')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='account.Country')),
                ('field_of_study', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account.FieldOfStudy')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.University')),
            ],
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='universities2',
            field=models.ManyToManyField(blank=True, through='consultants.StudyInfo', to='account.University'),
        ),
    ]
