# Generated by Django 2.2.3 on 2020-04-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0005_auto_20200411_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyinfo',
            name='order',
            field=models.PositiveIntegerField(help_text='Enter number above 0'),
        ),
    ]
