# Generated by Django 2.2.3 on 2020-04-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0006_auto_20200411_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyinfo',
            name='country',
        ),
    ]
