# Generated by Django 2.2.3 on 2020-04-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0008_auto_20200413_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyinfo',
            name='grade',
            field=models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('postdoc', 'Post Doc'), ('unknown', 'Unknown')], max_length=256),
        ),
    ]
