# Generated by Django 2.2.3 on 2020-04-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0009_auto_20200415_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantprofile',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='consultantprofile',
            name='field_of_studies',
        ),
        migrations.RemoveField(
            model_name='consultantprofile',
            name='universities',
        ),
    ]
