# Generated by Django 2.2.3 on 2020-04-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0009_auto_20200415_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantprofile',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='consultantprofile',
            name='field_of_studies',
        ),
        migrations.RemoveField(
            model_name='consultantprofile',
            name='universities2',
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='universities',
            field=models.ManyToManyField(blank=True, through='consultants.StudyInfo', to='account.University'),
        ),
    ]
