# Generated by Django 2.2.3 on 2020-04-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0010_auto_20200418_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultantprofile',
            old_name='universities2',
            new_name='universities',
        ),
    ]
