# Generated by Django 2.2.3 on 2020-05-15 08:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0011_auto_20200418_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='bio',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
