# Generated by Django 2.2.3 on 2020-02-12 08:15

from django.db import migrations
import enumfields.fields
import sNeeds.apps.customAuth.models


class Migration(migrations.Migration):
    dependencies = [
        ('customAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=enumfields.fields.EnumIntegerField(default=1,
                                                     enum=sNeeds.apps.customAuth.models.CustomUser.UserTypeChoices),
        ),
    ]
