# Generated by Django 2.2.3 on 2020-02-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
