# Generated by Django 2.2.3 on 2020-02-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0002_auto_20200212_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='time_slot_price',
            field=models.IntegerField(default=0),
        ),
    ]
