# Generated by Django 2.2.3 on 2020-02-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0003_consultantprofile_time_slot_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='time_slot_price',
            field=models.IntegerField(),
        ),
    ]
