# Generated by Django 2.2.3 on 2020-02-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0004_auto_20200212_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='time_slot_price',
            field=models.PositiveIntegerField(),
        ),
    ]
