# Generated by Django 2.2.3 on 2020-02-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0005_auto_20200211_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'consultant')], default=1),
        ),
    ]
