# Generated by Django 2.2.3 on 2019-07-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190703_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldofstudy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
