# Generated by Django 2.2.3 on 2019-07-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190703_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='field_of_study',
            field=models.ManyToManyField(to='account.FieldOfStudy'),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='university',
            field=models.ManyToManyField(to='account.University'),
        ),
    ]
