# Generated by Django 2.2.3 on 2019-07-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190703_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='university',
            name='country',
            field=models.CharField(default='ss', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='country',
            field=models.ManyToManyField(to='account.Country'),
        ),
    ]
