# Generated by Django 2.2.3 on 2019-07-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190703_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='aparat_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='slug',
            field=models.SlugField(default='temp', help_text='lowercase pls'),
            preserve_default=False,
        ),
    ]
