# Generated by Django 2.2.3 on 2019-07-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190704_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(default='temp', help_text='Lowercase pls'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='slug',
            field=models.SlugField(default='temp', help_text='Lowercase pls'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(default='temp', help_text='Lowercase pls'),
            preserve_default=False,
        ),
    ]
