# Generated by Django 2.2.3 on 2019-07-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190704_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultantprofile',
            old_name='country',
            new_name='countries',
        ),
        migrations.RenameField(
            model_name='consultantprofile',
            old_name='field_of_study',
            new_name='field_of_studies',
        ),
        migrations.RenameField(
            model_name='consultantprofile',
            old_name='university',
            new_name='universities',
        ),
    ]
