# Generated by Django 2.2.3 on 2019-07-06 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190705_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultantprofile',
            old_name='consultant',
            new_name='user',
        ),
    ]
