# Generated by Django 2.2.3 on 2019-07-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190722_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='picture',
            field=models.ImageField(upload_to='university_pictures'),
        ),
    ]
