# Generated by Django 2.2.3 on 2019-07-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_consultantprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
