# Generated by Django 2.2.3 on 2019-07-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_consultantprofile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='resume',
            field=models.FileField(null=True, upload_to='', verbose_name='account/resume'),
        ),
    ]
