# Generated by Django 2.2.3 on 2019-07-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20190726_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='profile_picture',
            field=models.ImageField(upload_to='media/account/consultant_profile_pictures'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='resume',
            field=models.FileField(null=True, upload_to='media/account/file/account/consultant_resume'),
        ),
        migrations.AlterField(
            model_name='country',
            name='picture',
            field=models.ImageField(upload_to='media/account/country_pictures'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='picture',
            field=models.ImageField(upload_to='media/account/field_of_study_pictures'),
        ),
        migrations.AlterField(
            model_name='university',
            name='picture',
            field=models.ImageField(upload_to='media/account/university_pictures'),
        ),
    ]
