# Generated by Django 2.2.3 on 2019-07-26 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0023_auto_20190726_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to='file/account/user_upload_file'),
        ),
        migrations.AlterUniqueTogether(
            name='userfile',
            unique_together={('user', 'type')},
        ),
    ]
