# Generated by Django 2.2.3 on 2019-07-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20190726_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='file/account/consultant_resume'),
        ),
        migrations.DeleteModel(
            name='UserFile',
        ),
    ]
