# Generated by Django 2.2.3 on 2019-08-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochats', '0004_auto_20190816_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='consultant_login_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_login_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
