# Generated by Django 2.2.3 on 2019-08-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videochats', '0006_auto_20190816_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user1_id',
            new_name='consultant_id',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='user2_id',
            new_name='user_id',
        ),
    ]
