# Generated by Django 2.1.3 on 2019-02-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField(help_text='120000 stands for 120 hezar tooman.')),
            ],
        ),
        migrations.CreateModel(
            name='SoldPublicClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('public_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_classes', to='class.PublicClass')),
            ],
        ),
    ]
