# Generated by Django 2.2.3 on 2019-08-25 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=64)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(limit_value=11, message='Phone number should be 11 numbers'), django.core.validators.MaxLengthValidator(limit_value=11, message='Phone number should be 11 numbers')])),
                ('university', models.CharField(max_length=256)),
                ('field_of_study', models.CharField(max_length=256)),
                ('resume', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
