# Generated by Django 2.2.3 on 2019-08-26 09:19

from django.db import migrations, models
import sNeeds.apps.consultant.models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMPConsultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=64)),
                ('phone_number', models.CharField(max_length=11)),
                ('university', models.CharField(max_length=256)),
                ('field_of_study', models.CharField(max_length=256)),
                ('resume', models.FileField(upload_to=sNeeds.apps.consultant.models.path_for_uploading_file)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Consultant',
        ),
    ]
