# Generated by Django 2.2.3 on 2020-03-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200229_0949'),
        ('store', '0005_auto_20200308_0756'),
        ('orders', '0003_auto_20200314_1128'),
        ('discounts', '0009_auto_20200319_1322'),
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='SoldWebinar',
        ),
        migrations.DeleteModel(
            name='Webinar',
        ),
    ]
