# Generated by Django 2.2.3 on 2020-05-16 13:33

from django.db import migrations
import enumfields.fields
import sNeeds.apps.notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='user_type',
            field=enumfields.fields.EnumIntegerField(default=None, enum=sNeeds.apps.notifications.models.NotificationType),
            preserve_default=False,
        ),
    ]
