# Generated by Django 2.2.3 on 2020-05-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200516_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
