# Generated by Django 2.2.3 on 2020-05-20 07:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20200516_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='data_json',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
