# Generated by Django 2.2.3 on 2020-05-20 07:15

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_emailnotification_data_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='data_json',
            field=jsonfield.fields.JSONField(default=None),
            preserve_default=False,
        ),
    ]
